

# Site Settings
locale                   : "en-US"
title                    : "PNU-PAC"
title_separator          : "-"
description              : "site of PNU-PAC"
url                      : "PNU-PAC.github.io"
